# Generated by Django 3.2 on 2021-04-14 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_additioanlimage_bb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditioanlImage',
            new_name='AdditionalImage',
        ),
    ]
